# Generated by Django 5.0.1 on 2024-03-30 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Fat', models.DecimalField(decimal_places=2, max_digits=4)),
                ('SNF', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Amount', models.DecimalField(decimal_places=3, max_digits=6)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk_app.user')),
            ],
        ),
    ]
