# Generated by Django 5.0.1 on 2024-03-31 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
