# Generated by Django 5.0.1 on 2024-04-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_app', '0002_alter_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Amount',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
