# Generated by Django 4.0.3 on 2024-05-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk_app', '0004_user_address_user_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Phone_No',
        ),
    ]
